DROP TABLE AVIS;
DROP TABLE AIMER;
DROP TABLE USER;
DROP TABLE RESTAURANT;

CREATE TABLE RESTAURANT (
  idR INT NOT NULL AUTO_INCREMENT,
  idJson INT NOT NULL,
  type VARCHAR(255) NULL,
  PRIMARY KEY (idR),
  UNIQUE KEY RESTAURANT_idR_key (idR)
);

CREATE TABLE USER (
  idU BIGINT NOT NULL AUTO_INCREMENT,
  nomU VARCHAR(255) NOT NULL,
  prenomU VARCHAR(255) NOT NULL,
  mailU VARCHAR(255) NOT NULL,
  typeU VARCHAR(255) NULL,
  mdp VARCHAR(255) NOT NULL,
  PRIMARY KEY (idU),
  UNIQUE KEY USER_idU_key (idU),
  UNIQUE KEY USER_mailU_key (mailU)
);

CREATE TABLE AIMER (
  idR INT NOT NULL AUTO_INCREMENT,
  idU INT NOT NULL,
  PRIMARY KEY (idR, idU),
  CONSTRAINT AIMER_idR_fkey FOREIGN KEY (idR) REFERENCES RESTAURANT(idR) ON DELETE CASCADE,
  CONSTRAINT AIMER_idU_fkey FOREIGN KEY (idU) REFERENCES USER(idU) ON DELETE CASCADE
);

CREATE TABLE AVIS (
  idU INT NOT NULL AUTO_INCREMENT,
  idR INT NOT NULL,
  note INT NULL,
  description VARCHAR(255) NULL,
  PRIMARY KEY (idU, idR),
  CONSTRAINT AVIS_idR_fkey FOREIGN KEY (idR) REFERENCES RESTAURANT(idR) ON DELETE CASCADE,
  CONSTRAINT AVIS_idU_fkey FOREIGN KEY (idU) REFERENCES USER(idU) ON DELETE CASCADE
);

INSERT INTO USER VALUES ('fonteny', 'noa', 'n@f', 'admin', 'admin');
