DROP TABLE IF EXISTS AVIS;
DROP TABLE IF EXISTS AIMER;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS GEO_POINT;
DROP TABLE IF EXISTS HORAIRES;
DROP TABLE IF EXISTS CONTACT;
DROP TABLE IF EXISTS INFORMATION_EN_PLUS;
DROP TABLE IF EXISTS RESTAURANT;



CREATE TABLE RESTAURANT (
  idR INT NOT NULL AUTO_INCREMENT,
  nameR VARCHAR(255) NOT NULL,
  siret VARCHAR(255) NOT NULL,
  typeR VARCHAR(255) NULL,
  PRIMARY KEY (idR),
  UNIQUE KEY (idR)
);

CREATE TABLE USERS (
  idU INT NOT NULL AUTO_INCREMENT,
  nomU VARCHAR(255) NOT NULL,
  prenomU VARCHAR(255) NOT NULL,
  mailU VARCHAR(255) NOT NULL,
  typeU VARCHAR(255) NULL,
  mdp VARCHAR(255) NOT NULL,
  PRIMARY KEY (idU),
  UNIQUE KEY (idU),
  UNIQUE KEY (mailU)
);

CREATE TABLE AIMER (
  idR INT NOT NULL,
  idU INT NOT NULL,
  PRIMARY KEY (idR, idU),
  CONSTRAINT FOREIGN KEY (idR) REFERENCES RESTAURANT(idR) ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY (idU) REFERENCES USERS(idU) ON DELETE CASCADE
);

CREATE TABLE AVIS (
  idU INT NOT NULL,
  idR INT NOT NULL,
  note INT NULL,
  description VARCHAR(255) NULL,
  dateA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (idU, idR),
  CONSTRAINT FOREIGN KEY (idR) REFERENCES RESTAURANT(idR) ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY (idU) REFERENCES USERS(idU) ON DELETE CASCADE
);

-- Création de la partie Restaurant
CREATE TABLE GEO_POINT (
  idR INT NOT NULL,
  latitude FLOAT NULL,
  longitude FLOAT NULL,
  commune VARCHAR(255),
  region VARCHAR(255),
  departement VARCHAR(255),
  code_commune VARCHAR(5),
  PRIMARY KEY (idR),
  CONSTRAINT FOREIGN KEY (idR) REFERENCES RESTAURANT(idR) ON DELETE CASCADE
);

CREATE TABLE HORAIRES (
  idR INT NOT NULL,
  jour VARCHAR(255) NOT NULL,
  heureOuverture TIME,
  heureFermeture TIME,
  PRIMARY KEY (idR, jour, heureOuverture),
  CONSTRAINT FOREIGN KEY (idR) REFERENCES RESTAURANT(idR) ON DELETE CASCADE
);

CREATE TABLE CONTACT (
  idR INT NOT NULL,
  telephone VARCHAR(255),
  mail VARCHAR(255),
  facebook VARCHAR(255),
  website VARCHAR(255),
  PRIMARY KEY (idR),
  CONSTRAINT FOREIGN KEY (idR) REFERENCES RESTAURANT(idR) ON DELETE CASCADE
);

CREATE TABLE INFORMATION_EN_PLUS (
  idR INT NOT NULL,
  typeI VARCHAR(255),
  description VARCHAR(255),
  PRIMARY KEY (idR, typeI),
  CONSTRAINT FOREIGN KEY (idR) REFERENCES RESTAURANT(idR) ON DELETE CASCADE
);