DROP TABLE IF EXISTS AVIS;
DROP TABLE IF EXISTS AIMER;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS RESTAURANT;

CREATE TABLE RESTAURANT (
  idR INT NOT NULL AUTO_INCREMENT,
  idJson INT NOT NULL,
  type VARCHAR(255) NULL,
  PRIMARY KEY (idR),
  UNIQUE KEY (idR)
);

CREATE TABLE USER (
  idU INT NOT NULL AUTO_INCREMENT,
  nomU VARCHAR(255) NOT NULL,
  prenomU VARCHAR(255) NOT NULL,
  mailU VARCHAR(255) NOT NULL,
  typeU VARCHAR(255) NULL,
  mdp VARCHAR(255) NOT NULL,
  PRIMARY KEY (idU),
  UNIQUE KEY (idU),
  UNIQUE KEY (mailU)
);

CREATE TABLE AIMER (
  idR INT NOT NULL,
  idU INT NOT NULL,
  PRIMARY KEY (idR, idU),
  CONSTRAINT FOREIGN KEY (idR) REFERENCES RESTAURANT(idR) ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY (idU) REFERENCES USER(idU) ON DELETE CASCADE
);

CREATE TABLE AVIS (
  idU INT NOT NULL,
  idR INT NOT NULL,
  note INT NULL,
  description VARCHAR(255) NULL,
  PRIMARY KEY (idU, idR),
  CONSTRAINT FOREIGN KEY (idR) REFERENCES RESTAURANT(idR) ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY (idU) REFERENCES USER(idU) ON DELETE CASCADE
);

INSERT INTO USER (nomU, prenomU, mailU, typeU, mdp) 
VALUES ('fonteny', 'noa', 'n@f', 'admin', 'admin');
